---

- name: Backup Running Config on Juniper SRX Firewall
  hosts: junos_fw
  tasks:
    - name: Grab running-config from Juniper SRX devices
      junipernetworks.junos.junos_config:
        backup: true
        backup_options:
          filename: "{{ inventory_hostname }}.cfg"
          dir_path: backup_config/

- name: Backup Running Config on ASA Firewall
  hosts: asa_fw
  tasks:
    - name: Grab running-config from Cisco ASA device
      cisco.asa.asa_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}.cfg"
          dir_path: backup_config/

