---

R1:
  hostname: 192.168.1.100
  groups:
      - ios
      - euro_group
R2:
  hostname: 192.168.1.101
  groups:
      - eos
      - usa_group
R3:
  hostname: 192.168.1.102
  groups:
      - ios-xe
      - euro_group

